-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF AS F
INNER JOIN (
    SELECT FLAVOR AS JULY_FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS J
ON F.FLAVOR = J.JULY_FLAVOR
ORDER BY (TOTAL_ORDER + JULY_TOTAL_ORDER) DESC
LIMIT 3